test_suites:
    - name: e2e-classic
      script_path: /root/okta/samples-js-react/scripts/e2e
      sort_order: '1'
      timeout: '10'
      script_name: e2e-classic
      criteria: OPTIONAL
      queue_name: small

    - name: e2e-oie
      script_path: /root/okta/samples-js-react/scripts/e2e
      sort_order: '1'
      timeout: '10'
      script_name: e2e-oie
      criteria: OPTIONAL
      queue_name: small

    - name: semgrep
      script_path: /root/okta/samples-js-react/scripts
      sort_order: '3'
      timeout: '10'
      script_name: semgrep
      criteria: MERGE
      queue_name: small

    - name: synk
      script_path: /root/okta/samples-js-react/scripts
      script_name: synk
      sort_order: '3'
      timeout: '200'
      criteria: MAINLINE
      queue_name: small
      trigger: AUTO