/*!
 * Copyright (c) 2015-2016, Okta, Inc. and/or its affiliates. All rights reserved.
 * The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
 *
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and limitations under the License.
 */
/* eslint-disable */

/* --- This file was auto-generated by generate-keys.js --- */
module.exports = {
  privatePem: `-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAqBWULNVovIxqRRAd0JOm2RJbRC6zknGRtJQwV2HdS/GXUtJT
9jKTRNI6ed15HCtV9njDOTw5P10EStYbu+jriGiaJbPPLgwEvTEwdM3EIReVuPFB
sVUK1NarUn71nPIO+Zk+XzwI4J4WUTbxs+ycOsoMa6uSgEoTcE8qwKHUJretBA4n
otCyAbopFkwI9LtCZG0JcGMULVtO/mpgaGSkytIHWp0re4jUfEsOCxtGp/J+GRf2
CCB9FZJwbfO4/6fCH0Sh03qGcP0iA6G1nEJoklvTdfpeqttJWUmYbSpCrbksUT4i
IAb+7Y2pcEMPh9sdzfTA9PeWCPbUOz0XXcUymwIDAQABAoIBAD3aewWonvtLnMu/
a4lW3H5jL+y+VtycKGdQZR2y6NHKnMoglj8yS1l3F4fDBY9lLyQdOpI0ZEi5/Rth
ASG8S/iNrbQUIDisuY25rUA+fF9FI5bESU1toyfBu5gHGnFf7jzRtM8s84NdCY9n
bbitaKyFr95ra+UD3XVl3LC4nK6GLlm/loQxTTvAXMbRfGIxLnK8S4e+4V5zsNTY
fX+nWRXyhgV5hWN7geSU6EPxrlc9zdBDkL3VCYqXubzFY7J8fus6BnRYVBeTmYP/
h0q+KqeJE6dkRpjfDVGZLy7KcZR7CbbxJU+69x9CaNzgQLE3DeT9n1LMlv2g7Eyb
g6KlpuECgYEA0dRLAtZwIT2BtoU00rzzpAPKlwASKaJeehbykEOUJeXQWq3ES6vk
gzXIrQWp3/2jkfgAyaIzWKmFKG9qe5q02DNZD/oGwps2lUSO9TDz5/XWrF4E3rk0
QJqUHvNX88O0SV3WwnPcRyw1CvChM/SVWkD5HpsQAG1OIke9Owt+hfECgYEAzRHJ
UZ3q6nONKNrXIJv9PQogLYwnl1GEj8YtHLqaaln/afMnldinsGUPp5HQsuGW2TZ3
Bq3a+ecTcer+IFe1xHxWNejgw9NQ8jVCYLDh8Hw2DxaZ3H5uZsv+UQBenMEPZ2H7
HAZkB4C0zvPgAIVWezA2s++F2C64DkC8T106RUsCgYEAoN2k9HP6W0GQZKITMU1z
bNcLRmDji8/Tpr5ZEIj+118tMZfu2iTaeE2PoDarWfJWqN39nJghzWOJlsp0VHbz
Fp2nNjx1WlUsr5t0Dj6Nf9RV1KfwC+DpUm4wCNp/H392hJjQwRuaUWZu9AgvTmnA
5wTQ+MngprMmJ9ngFZhmU8ECgYEAiy5HNN25UuaaJ+BfogI9HfCBZmh5dnodPneC
prz/kK8EayRc+ZbSOSZeOZz9yGrTtxkAL8hPlsz+pZKYZ9sfwvugh3ZHFqGVjs4W
/wkOT+n9xr/QLZah16McOF3H2RwvGDun8p1jxrPUA6IBpljZGULf3b/zV4Zd5U6K
gFMF+YECgYEAzcXWuSKfC+eZFmRliIbYbDXaBM8M0tRkR1PBzPtJKmYz6cnZC7NV
QRE51iVToptXReAjT1G3DZrtfJ459ecrXyXfnEC0UPUF8b4rB5jvm+WvFJkc6sgi
Lx4JX5RfJHp5mUXrws776sgvshQuBQXa/W51CGU81UOG1JkRF3drdJM=
-----END RSA PRIVATE KEY-----
`,
  publicPem: `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqBWULNVovIxqRRAd0JOm
2RJbRC6zknGRtJQwV2HdS/GXUtJT9jKTRNI6ed15HCtV9njDOTw5P10EStYbu+jr
iGiaJbPPLgwEvTEwdM3EIReVuPFBsVUK1NarUn71nPIO+Zk+XzwI4J4WUTbxs+yc
OsoMa6uSgEoTcE8qwKHUJretBA4notCyAbopFkwI9LtCZG0JcGMULVtO/mpgaGSk
ytIHWp0re4jUfEsOCxtGp/J+GRf2CCB9FZJwbfO4/6fCH0Sh03qGcP0iA6G1nEJo
klvTdfpeqttJWUmYbSpCrbksUT4iIAb+7Y2pcEMPh9sdzfTA9PeWCPbUOz0XXcUy
mwIDAQAB
-----END PUBLIC KEY-----
`,
  publicJwk: {"kty":"RSA","n":"qBWULNVovIxqRRAd0JOm2RJbRC6zknGRtJQwV2HdS_GXUtJT9jKTRNI6ed15HCtV9njDOTw5P10EStYbu-jriGiaJbPPLgwEvTEwdM3EIReVuPFBsVUK1NarUn71nPIO-Zk-XzwI4J4WUTbxs-ycOsoMa6uSgEoTcE8qwKHUJretBA4notCyAbopFkwI9LtCZG0JcGMULVtO_mpgaGSkytIHWp0re4jUfEsOCxtGp_J-GRf2CCB9FZJwbfO4_6fCH0Sh03qGcP0iA6G1nEJoklvTdfpeqttJWUmYbSpCrbksUT4iIAb-7Y2pcEMPh9sdzfTA9PeWCPbUOz0XXcUymw","e":"AQAB","alg":"RS256","use":"sig","kid":"TEST_KID"}
};
